package com.je3l.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImagesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagesAllPropertiesEquals(Images expected, Images actual) {
        assertImagesAutoGeneratedPropertiesEquals(expected, actual);
        assertImagesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagesAllUpdatablePropertiesEquals(Images expected, Images actual) {
        assertImagesUpdatableFieldsEquals(expected, actual);
        assertImagesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagesAutoGeneratedPropertiesEquals(Images expected, Images actual) {
        assertThat(expected)
            .as("Verify Images auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagesUpdatableFieldsEquals(Images expected, Images actual) {
        assertThat(expected)
            .as("Verify Images relevant properties")
            .satisfies(e -> assertThat(e.getUrl()).as("check url").isEqualTo(actual.getUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagesUpdatableRelationshipsEquals(Images expected, Images actual) {
        assertThat(expected)
            .as("Verify Images relationships")
            .satisfies(e -> assertThat(e.getAliment()).as("check aliment").isEqualTo(actual.getAliment()));
    }
}
